### ISSUE TITLE
getTimetables.py doesn't work anymore

### ISSUE THREAD

**Issue by DanSirbu** [morinted/schedule-generator#14]
Website is up but there is no semester to select in the application.

![image](https://cloud.githubusercontent.com/assets/7788433/21705121/e3c36164-d38b-11e6-869b-017fc6392e72.png)

**Comment by davidschlachter** [comment]
Thanks for catching this! It looks like the `course-download` scripts haven't been working since Nov 1 (https://schlachter.ca/schedgen/archive/). It's probably related to the changes done to uOZone/infoWeb on November 7. I'll take a look at this over the next few days.

In the meantime, I've restored the `courses-2016-11-01.tar.gz` archive to the server, so you should be able to use the tool until I get the automatic updates working again.

**Comment by davidschlachter** [comment]
I've updated both `getCourses.py` and `getTimetables.py` for the new format of the [Course Timetables](https://web30.uottawa.ca/v3/SITS/timetable/Search.aspx) website. The biggest change was that the URL format now refers to courses by an integer ID instead of by course code.

However, the server crashes when loading newly downloaded timetables. I think this may be an issue with activities being zero-indexed instead of one-indexed, or possibly because of conflicting sections, courses with no activities, etc (formerly I cleaned this up with a bash script but I haven't updated it yet). I'll take a look at this in the coming weeks (before registration for Summer 2017 starts).

Relevant commits: eb89355fb2f8026c604efd5b884b201d5d5b4069, a00c02050caffac57b15a550eebfd532f8b808c2

**Comment by morinted** [comment]
Integer ID instead of course code is such a cruddy change on their part.

**Comment by davidschlachter** [comment]
The remaining issues were the creation of duplicate sections (f9de06840630445b354e7a2ef4ddbf39df8cbab2) and the `one_dgd`-type bits not being set (3b64e1a3b667bdb1e15497c06db6d66a269c120c, 1fb278de2968bf17eb5fa7467d85d9d946f332d3). Everything back to normal and the timetables are auto-updating server-side again.
