### ISSUE TITLE
Unable to connect

### ISSUE THREAD

**Issue by ReidTait** [morinted/schedule-generator#21]
Hi!

Looks like the program is having trouble connecting to the server. Any chance you could look into this when you have a chance?

Thanks 👍

**Comment by davidschlachter** [comment]
I've been doing some server maintenance and hope to have it online again tomorrow or the next day. I'll close the issue when everything's back up!

**Comment by davidschlachter** [comment]
The schedule-generator server is back up again — let me know if there are any problems!

Automatic refreshing of schedules might take a few weeks since there isn't a Selenium Chrome driver for FreeBSD (new server's OS). I'll update them manually once in a while until I re-write the scraper, virtualize, or find another solution.
