### ISSUE TITLE
'schedule' div should be treated as a section, not a semester

### ISSUE THREAD

**Issue by SheikhIV** [morinted/schedule-generator#25]
The schedule generator works great but the CHM1311 labs are not showing up as of yet.

Thanks again!!

**Comment by davidschlachter** [comment]
The uOttawa timetables site changed the contents of a particular divider to represent sections instead of semesters. The section ID should only be retrieved once per 'schedule' div, not for each `tr`. For CHM1311 all the labs have section 'Z', so right now they're going into a made-up section instead of being available for each lecture section.

**Comment by davidschlachter** [comment]
Partially addressed in f42f7a4cfca275c4cad7ce53da075f063f874c86, but need to fix activity numbers only being captured as single digits.

**Comment by davidschlachter** [comment]
Fixed the activity numbers in 2fffb81a08910079d98741ca9827dda0a3fedc26.

Note that CHM1311 is a bit strange since the lab sections all have one lab day that's shorter than the others, but all the labs in a set have the same section number. This causes duplicate schedules for each lab section, one with a short lab, one with a long one. I'm not sure how this would be addressed so I'm closing the issue, but just something to keep in mind.

Thanks for reporting this!
