### ISSUE TITLE
Course block heights incorrect

### ISSUE THREAD

**Issue by OttUDad** [morinted/schedule-generator#27]
When generating schedules for Fall 2018 the display of the classes that are "90 minutes" are not displaying for the full time i.e. if the class is from 9-10:20 it only display from 9-10 ... examples are ADM4338, ADM3301.  Evening sections are displaying fine.

**Comment by davidschlachter** [comment]
Are you seeing this in the Schedule Generator app, or on the [uOttawa timetables website](https://web30.uottawa.ca/v3/SITS/timetable/Search.aspx)? As far as I can tell all the lectures for these courses are 90 minutes long in the database for the app.

![capture d ecran 2018-05-21 a 11 38 40](https://user-images.githubusercontent.com/8271268/40316359-17cb9590-5cec-11e8-841b-30efd8a2277a.png)

**Comment by OttUDad** [comment]
I clicked on the download the program for windows, mac and Linux.  From the course list I selected the ADM3333, ADM3334,  ADM3337 and ADM4338 and added them and then selected generate schedules.  The schedule displays on the UI with 2 lines for the 90 minute class ie ADM433A on line 1 and LEC 0 on line 2.  The slot it picks for Monday is 11:30 - 12:30 instead of all the way to 1:00
![capture](https://user-images.githubusercontent.com/39484983/40334959-211d3caa-5d2f-11e8-90a6-343d8b22952f.PNG)

**Comment by davidschlachter** [comment]
Yeah, I see now — this is affecting all courses actually. Exporting the schedule or checking section details (e.g. by double clicking course names in the 'Mandatory/Optional Courses' lists) will show the correct lengths, but the end times are all being rounded down instead of up to the nearest half hour.

**Comment by davidschlachter** [comment]
Fixed in 9b2fea81d1a3147d687d166ec7ea9d40b4f8e962 by just changing all hh:20 to hh:30 and hh:50 to (hh+1):00 when fetching schedules. Not the most elegant solution but this way nobody has to re-download the app to get schedules to display right.

![capture d ecran 2018-05-22 a 19 18 20](https://user-images.githubusercontent.com/8271268/40395269-42c7532e-5df5-11e8-950e-4f7c6da2af01.png)
