### ISSUE TITLE
Searching for any ELG courses returns nothing

### ISSUE THREAD

**Issue by Abhay97** [morinted/schedule-generator#36]

**Comment by Abhay97** [comment]
csi also does not show up.

**Comment by davidschlachter** [comment]
This was due to regex error in the new course download script `updateDatabase.py` that limited subject codes to nine subjects per letter of the alphabet. I've just changed `\d"` to `\d+"` on [line 51](https://github.com/morinted/schedule-generator/blob/86cb9bf151d6a7af089abffb791aa67ed82d4530/course-download/updateDatabase.py#L51) and am scraping new timetables now. This should be fixed in a few hours and I'll close the issue when the new timetables are in place.

(Just for reference, the schedules are automatically updated every four days and archived to https://schlachter.ca/schedgen/archive/ )

**Comment by Abhay97** [comment]
cheers! glad it was a quick fix.

**Comment by davidschlachter** [comment]
Thanks again for reporting, the courses should all be there now.
