### ISSUE TITLE
Law classes not populating

### ISSUE THREAD

**Issue by happysunshinekid** [morinted/schedule-generator#42]
E.g CML2313A
CML2312D

Thanks!

**Comment by davidschlachter** [comment]
I can't see those courses when I search the [uOttawa timetables website](https://uocampus.public.uottawa.ca/psp/csprpr9pub/EMPLOYEE/HRMS/c/UO_SR_AA_MODS.UO_PUB_CLSSRCH.GBL?languageCd=ENG) (searching 2nd year courses with CML course code). If I missed something and they are listed, let me know; otherwise they won't appear in the timetables generator if the schedules aren't yet (or currently) available.

(Note that we update the timetables every four days, so when these courses appear on the uOttawa site they'll appear in the schedule generator soon afterwards)

**Comment by sclel016** [comment]
Seems the uOttawa Common Law program has their own website for course search (who knows why...)
https://commonlaw.uottawa.ca/en/students/student-centre/course_search_engine

**Comment by davidschlachter** [comment]
Strange, I'll try to keep track of / investigate if the information gets integrated into the general uOttawa timetables site. If not, another scraper may be required for CML courses.

**Comment by davidschlachter** [comment]
Both CML2313 and CML2312 are now on the regular uOttawa timetables website.
