### ISSUE TITLE
Reboot server please

### ISSUE THREAD

**Issue by dimonoid** [morinted/schedule-generator#51]
Hello, the program cannot connect to your server. Could you please restart it? Also there is currently new schedule posted for the next year, maybe that is the cause of issue?

**Comment by davidschlachter** [comment]
The server automatically restarts every couple hours. However, checking the logs, it currently appears to be crashing each time a new connection is made. As you guessed, this is usually because of a problem with the schedules database, but the specific cause is difficult to determine.

While I've reverted the course database to what seemed to be the last known-good version, I'm still seeing the crashes and can't get a client to connect. I'll have to open up the server in a debugger (maybe tomorrow) to get a better idea of what's going on.

**Comment by davidschlachter** [comment]
I rebuilt the server environment and it looks like this is resolved for now. Thank you for your report! Keep in mind that courses with DGDs only (no lab/lecture) may not be able to return schedules (open bug #50).

**Comment by davidschlachter** [comment]
FYI the issue with DGD-only courses is now fixed, most schedules should generate fine now.

**Comment by dimonoid** [comment]
Something is wrong, again...

**Comment by davidschlachter** [comment]
Server location had an extended power outage this afternoon, back online now.

**Comment by dimonoid** [comment]
Thanks
